USB_REQ_TYP_IN = 0x80	#control IN, device to host
USB_REQ_TYP_OUT = 0x00	#control OUT, host to device
USB_REQ_TYP_READ = 0x80	#control read, device to host
USB_REQ_TYP_WRITE = 0x00	#control write, host to device
USB_REQ_TYP_MASK = 0x60	#bit mask of request type
USB_REQ_TYP_STANDARD = 0x00
USB_REQ_TYP_CLASS = 0x20
USB_REQ_TYP_VENDOR = 0x40
USB_REQ_TYP_RESERVED = 0x60
USB_REQ_RECIP_MASK = 0x1F	#bit mask of request recipient
USB_REQ_RECIP_DEVICE = 0x00
USB_REQ_RECIP_INTERF = 0x01
USB_REQ_RECIP_ENDP = 0x02
USB_REQ_RECIP_OTHER = 0x03

#USB standard device request code
USB_GET_STATUS = 0x00
USB_CLEAR_FEATURE = 0x01
USB_SET_FEATURE = 0x03
USB_SET_ADDRESS = 0x05
USB_GET_DESCRIPTOR = 0x06
USB_SET_DESCRIPTOR = 0x07
USB_GET_CONFIGURATION = 0x08
USB_SET_CONFIGURATION = 0x09
USB_GET_INTERFACE = 0x0A
USB_SET_INTERFACE = 0x0B
USB_SYNCH_FRAME = 0x0C

#USB descriptor type
USB_DESCR_TYP_DEVICE = 0x01
USB_DESCR_TYP_CONFIG = 0x02
USB_DESCR_TYP_STRING = 0x03
USB_DESCR_TYP_INTERF = 0x04
USB_DESCR_TYP_ENDP = 0x05
USB_DESCR_TYP_QUALIF = 0x06
USB_DESCR_TYP_SPEED = 0x07
USB_DESCR_TYP_OTG = 0x09
USB_DESCR_TYP_HID = 0x21
USB_DESCR_TYP_REPORT = 0x22
USB_DESCR_TYP_PHYSIC = 0x23
USB_DESCR_TYP_CS_INTF = 0x24
USB_DESCR_TYP_CS_ENDP = 0x25
USB_DESCR_TYP_HUB = 0x29

#USB PID
USB_PID_NULL = 0x00    #reserved PID
USB_PID_SOF = 0x05
USB_PID_SETUP = 0x0D
USB_PID_IN = 0x09
USB_PID_OUT = 0x01
USB_PID_ACK = 0x02
USB_PID_NAK = 0x0A
USB_PID_STALL = 0x0E
USB_PID_DATA0 = 0x03
USB_PID_DATA1 = 0x0B
USB_PID_PRE = 0x0C

#Host FSM states
S_DISCONNECTED = 0x00
S_RESET_START = 0x01
S_RESET_END = 0x02
S_SET_SPEED = 0x03
S_CONNECTED = 0x04
S_GET_DEV_DESCR = 0x05
S_SET_ADDR = 0x06
S_CONFIGURE = 0x07
S_IDLE = 0x08
S_RUN = 0x09

usb_request_dev_descr = [USB_REQ_TYP_IN | USB_REQ_TYP_STANDARD | USB_REQ_RECIP_DEVICE, USB_GET_DESCRIPTOR, 0x00, USB_DESCR_TYP_DEVICE, 0x00, 0x00, 18, 0x00]
usb_request_config_descr = [USB_REQ_TYP_IN | USB_REQ_TYP_STANDARD | USB_REQ_RECIP_DEVICE, USB_GET_DESCRIPTOR, 0x00, USB_DESCR_TYP_CONFIG, 0x00, 0x00, 9, 0x00]
