/*
 * ch32v203_flash.c
 *
 *  Created on: Mar 15, 2026
 *      Author: dragomir
 */
#include "ch32v20x.h"
#include "ch32v203_flash.h"

#define FLASH_KEY1 0x45670123
#define FLASH_KEY2 0xCDEF89AB

void flash_unlock(void)
{
    FLASH->KEYR = FLASH_KEY1;
    FLASH->KEYR = FLASH_KEY2;
}

void flash_lock(void)
{
    FLASH->CTLR |= FLASH_CTLR_LOCK;
}

void flash_write_single16(uint32_t address, uint16_t val)
{
	FLASH->CTLR = (FLASH->CTLR & ~(FLASH_CTLR_PG | FLASH_CTLR_PER | FLASH_CTLR_MER | FLASH_CTLR_OPTPG | FLASH_CTLR_OPTER | FLASH_CTLR_PAGE_PG | FLASH_CTLR_PAGE_ER | FLASH_CTLR_PAGE_BER32 | FLASH_CTLR_PAGE_BER64)) | FLASH_CTLR_PG;
	*(volatile uint16_t *)address = val;
	while(FLASH->STATR & FLASH_STATR_BSY);
	FLASH->CTLR &= ~(FLASH_CTLR_PG | FLASH_CTLR_PER | FLASH_CTLR_MER | FLASH_CTLR_OPTPG | FLASH_CTLR_OPTER | FLASH_CTLR_PAGE_PG | FLASH_CTLR_PAGE_ER | FLASH_CTLR_PAGE_BER32 | FLASH_CTLR_PAGE_BER64);
}

void flash_write16(uint32_t address, uint16_t* src, uint16_t num_words)
{
	FLASH->CTLR = (FLASH->CTLR & ~(FLASH_CTLR_PG | FLASH_CTLR_PER | FLASH_CTLR_MER | FLASH_CTLR_OPTPG | FLASH_CTLR_OPTER | FLASH_CTLR_PAGE_PG | FLASH_CTLR_PAGE_ER | FLASH_CTLR_PAGE_BER32 | FLASH_CTLR_PAGE_BER64)) | FLASH_CTLR_PG;
	while(num_words)
	{
		*(volatile uint16_t *)address = *src;
		while(FLASH->STATR & FLASH_STATR_BSY);
		++src;
		address += 2;
		--num_words;
	}
	FLASH->CTLR &= ~(FLASH_CTLR_PG | FLASH_CTLR_PER | FLASH_CTLR_MER | FLASH_CTLR_OPTPG | FLASH_CTLR_OPTER | FLASH_CTLR_PAGE_PG | FLASH_CTLR_PAGE_ER | FLASH_CTLR_PAGE_BER32 | FLASH_CTLR_PAGE_BER64);
}

//HINT: Erases a 4KB page
void flash_erase_page(uint32_t address)
{
	FLASH->CTLR = (FLASH->CTLR & ~(FLASH_CTLR_PG | FLASH_CTLR_PER | FLASH_CTLR_MER | FLASH_CTLR_OPTPG | FLASH_CTLR_OPTER | FLASH_CTLR_PAGE_PG | FLASH_CTLR_PAGE_ER | FLASH_CTLR_PAGE_BER32 | FLASH_CTLR_PAGE_BER64)) | FLASH_CTLR_PER;
	FLASH->ADDR = address;
	FLASH->CTLR |= FLASH_CTLR_STRT;
	while(FLASH->STATR & FLASH_STATR_BSY);
	FLASH->CTLR &= ~(FLASH_CTLR_PG | FLASH_CTLR_PER | FLASH_CTLR_MER | FLASH_CTLR_OPTPG | FLASH_CTLR_OPTER | FLASH_CTLR_PAGE_PG | FLASH_CTLR_PAGE_ER | FLASH_CTLR_PAGE_BER32 | FLASH_CTLR_PAGE_BER64);
}

//HINT: erases pages from start_addr up to and including the page which contains end_addr
void flash_erase_range(uint32_t start_addr, uint32_t end_addr)
{
	for(uint32_t page = start_addr; page <= end_addr; page += 256)
	{
		flash_erase_page(page);
	}
}

//Erases the whole chip, must be run from SRAM
void flash_chip_erase(void)
{
	FLASH->CTLR = (FLASH->CTLR & ~(FLASH_CTLR_PG | FLASH_CTLR_PER | FLASH_CTLR_MER | FLASH_CTLR_OPTPG | FLASH_CTLR_OPTER | FLASH_CTLR_PAGE_PG | FLASH_CTLR_PAGE_ER | FLASH_CTLR_PAGE_BER32 | FLASH_CTLR_PAGE_BER64)) | FLASH_CTLR_MER;
	FLASH->CTLR |= FLASH_CTLR_STRT;
	while(FLASH->STATR & FLASH_STATR_BSY);
	FLASH->CTLR &= ~(FLASH_CTLR_PG | FLASH_CTLR_PER | FLASH_CTLR_MER | FLASH_CTLR_OPTPG | FLASH_CTLR_OPTER | FLASH_CTLR_PAGE_PG | FLASH_CTLR_PAGE_ER | FLASH_CTLR_PAGE_BER32 | FLASH_CTLR_PAGE_BER64);
}

void flash_fast_unlock(void)
{
	FLASH->KEYR = FLASH_KEY1;
	FLASH->KEYR = FLASH_KEY2;
	FLASH->MODEKEYR = FLASH_KEY1;
	FLASH->MODEKEYR = FLASH_KEY2;
}

void flash_fast_lock(void)
{
	FLASH->CTLR |= FLASH_CTLR_FAST_LOCK;
}

//HINT: Writes a 256-byte page. Source data must be 32-bit word aligned.
void flash_fast_write_page(uint32_t address, uint32_t* src)
{
	uint8_t count = 64;
	FLASH->CTLR = (FLASH->CTLR & ~(FLASH_CTLR_PG | FLASH_CTLR_PER | FLASH_CTLR_MER | FLASH_CTLR_OPTPG | FLASH_CTLR_OPTER | FLASH_CTLR_PAGE_PG | FLASH_CTLR_PAGE_ER | FLASH_CTLR_PAGE_BER32 | FLASH_CTLR_PAGE_BER64)) | FLASH_CTLR_PAGE_PG;
	do
	{
		*(uint32_t *)address = *src;
		address += 4;
		src += 1;
		count -= 1;
		while(FLASH->STATR & FLASH_STATR_WRBSY);
	} while(count);
	FLASH->CTLR |= FLASH_CTLR_PG_STRT;
	while(FLASH->STATR & FLASH_STATR_BSY);
	FLASH->CTLR &= ~(FLASH_CTLR_PG | FLASH_CTLR_PER | FLASH_CTLR_MER | FLASH_CTLR_OPTPG | FLASH_CTLR_OPTER | FLASH_CTLR_PAGE_PG | FLASH_CTLR_PAGE_ER | FLASH_CTLR_PAGE_BER32 | FLASH_CTLR_PAGE_BER64);
}

//HINT: Erases a 256 byte page
void flash_fast_erase_page(uint32_t address)
{
	address &= 0xFFFFFF00;	//not sure if needed
	FLASH->CTLR = (FLASH->CTLR & ~(FLASH_CTLR_PG | FLASH_CTLR_PER | FLASH_CTLR_MER | FLASH_CTLR_OPTPG | FLASH_CTLR_OPTER | FLASH_CTLR_PAGE_PG | FLASH_CTLR_PAGE_ER | FLASH_CTLR_PAGE_BER32 | FLASH_CTLR_PAGE_BER64)) | FLASH_CTLR_PAGE_ER;
	FLASH->ADDR = address;
	FLASH->CTLR |= FLASH_CTLR_STRT;
	while(FLASH->STATR & FLASH_STATR_BSY);
	FLASH->CTLR &= ~(FLASH_CTLR_PG | FLASH_CTLR_PER | FLASH_CTLR_MER | FLASH_CTLR_OPTPG | FLASH_CTLR_OPTER | FLASH_CTLR_PAGE_PG | FLASH_CTLR_PAGE_ER | FLASH_CTLR_PAGE_BER32 | FLASH_CTLR_PAGE_BER64);
}

//HINT: Erases a 32KB page
void flash_fast_erase_block_32kb(uint32_t address)
{
	address &= 0xFFFF8000;	//not sure if needed
	FLASH->CTLR = (FLASH->CTLR & ~(FLASH_CTLR_PG | FLASH_CTLR_PER | FLASH_CTLR_MER | FLASH_CTLR_OPTPG | FLASH_CTLR_OPTER | FLASH_CTLR_PAGE_PG | FLASH_CTLR_PAGE_ER | FLASH_CTLR_PAGE_BER32 | FLASH_CTLR_PAGE_BER64)) | FLASH_CTLR_PAGE_BER32;
	FLASH->ADDR = address;
	FLASH->CTLR |= FLASH_CTLR_STRT;
	while(FLASH->STATR & FLASH_STATR_BSY);
	FLASH->CTLR &= ~(FLASH_CTLR_PG | FLASH_CTLR_PER | FLASH_CTLR_MER | FLASH_CTLR_OPTPG | FLASH_CTLR_OPTER | FLASH_CTLR_PAGE_PG | FLASH_CTLR_PAGE_ER | FLASH_CTLR_PAGE_BER32 | FLASH_CTLR_PAGE_BER64);
}

//HINT: Erases a 64KB page
void flash_fast_erase_block_64kb(uint32_t address)
{
	address &= 0xFFFF0000;	//not sure if needed
	FLASH->CTLR = (FLASH->CTLR & ~(FLASH_CTLR_PG | FLASH_CTLR_PER | FLASH_CTLR_MER | FLASH_CTLR_OPTPG | FLASH_CTLR_OPTER | FLASH_CTLR_PAGE_PG | FLASH_CTLR_PAGE_ER | FLASH_CTLR_PAGE_BER32 | FLASH_CTLR_PAGE_BER64)) | FLASH_CTLR_PAGE_BER64;
	FLASH->ADDR = address;
	FLASH->CTLR |= FLASH_CTLR_STRT;
	while(FLASH->STATR & FLASH_STATR_BSY);
	FLASH->CTLR &= ~(FLASH_CTLR_PG | FLASH_CTLR_PER | FLASH_CTLR_MER | FLASH_CTLR_OPTPG | FLASH_CTLR_OPTER | FLASH_CTLR_PAGE_PG | FLASH_CTLR_PAGE_ER | FLASH_CTLR_PAGE_BER32 | FLASH_CTLR_PAGE_BER64);
}

void flash_unlock_option_bytes(void)
{
	FLASH->KEYR = FLASH_KEY1;
	FLASH->KEYR = FLASH_KEY2;
	FLASH->OBKEYR = FLASH_KEY1;
	FLASH->OBKEYR = FLASH_KEY2;
}

//HINT: The flash controller uses only the low byte, the high byte is always the complement of the low byte.
void flash_write_option_bytes(uint32_t address, uint16_t val)
{
	FLASH->CTLR = (FLASH->CTLR & ~(FLASH_CTLR_PG | FLASH_CTLR_PER | FLASH_CTLR_MER | FLASH_CTLR_OPTPG | FLASH_CTLR_OPTER | FLASH_CTLR_PAGE_PG | FLASH_CTLR_PAGE_ER | FLASH_CTLR_PAGE_BER32 | FLASH_CTLR_PAGE_BER64)) | FLASH_CTLR_OPTPG;
	*(volatile uint16_t *)address = val;
	while(FLASH->STATR & FLASH_STATR_BSY);
	FLASH->CTLR &= ~(FLASH_CTLR_PG | FLASH_CTLR_PER | FLASH_CTLR_MER | FLASH_CTLR_OPTPG | FLASH_CTLR_OPTER | FLASH_CTLR_PAGE_PG | FLASH_CTLR_PAGE_ER | FLASH_CTLR_PAGE_BER32 | FLASH_CTLR_PAGE_BER64);
}

//HINT: erases the entire 128-byte option byte region
void flash_erase_option_bytes(void)
{
	FLASH->CTLR = (FLASH->CTLR & ~(FLASH_CTLR_PG | FLASH_CTLR_PER | FLASH_CTLR_MER | FLASH_CTLR_OPTPG | FLASH_CTLR_OPTER | FLASH_CTLR_PAGE_PG | FLASH_CTLR_PAGE_ER | FLASH_CTLR_PAGE_BER32 | FLASH_CTLR_PAGE_BER64)) | FLASH_CTLR_OPTER;
	FLASH->CTLR |= FLASH_CTLR_STRT;
	while(FLASH->STATR & FLASH_STATR_BSY);
	FLASH->CTLR &= ~(FLASH_CTLR_PG | FLASH_CTLR_PER | FLASH_CTLR_MER | FLASH_CTLR_OPTPG | FLASH_CTLR_OPTER | FLASH_CTLR_PAGE_PG | FLASH_CTLR_PAGE_ER | FLASH_CTLR_PAGE_BER32 | FLASH_CTLR_PAGE_BER64);
}
